# Generated by Django 5.2.5 on 2025-08-26 21:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dentist_info_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dentist",
            name="Profile_img",
            field=models.ImageField(blank=True, null=True, upload_to="media/images/"),
        ),
        migrations.AlterField(
            model_name="dentist",
            name="User_id",
            field=models.CharField(
                max_length=6,
                unique=True,
                validators=[django.core.validators.MinLengthValidator(6)],
            ),
        ),
    ]
