# Generated by Django 5.2.5 on 2025-08-31 23:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dentist_info_app", "0002_dentist_profile_img_alter_dentist_user_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Gmail", models.EmailField(max_length=250)),
                (
                    "Dentist_ID",
                    models.CharField(
                        max_length=6,
                        unique=True,
                        validators=[django.core.validators.MinLengthValidator(6)],
                    ),
                ),
                ("Date", models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name="dentist",
            name="Profile_img",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
