# Generated by Django 5.2.5 on 2025-09-20 12:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dentist_info_app", "0004_booking_appointment_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="Date_now",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
