# Generated by Django 5.2.5 on 2025-09-21 20:00

import dentist_info_app.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dentist_info_app", "0006_rename_date_booking_date_booking_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="Patient",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Booking_history",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="booking",
            name="Appointment_ID",
            field=models.CharField(
                default=dentist_info_app.models.Booking.Generate_appointment_id,
                max_length=10,
                unique=True,
            ),
        ),
    ]
