# Generated by Django 5.2.5 on 2025-09-23 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dentist_info_app", "0007_booking_patient_alter_booking_appointment_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="Dentist_ID",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="dentist_info_app.dentist",
            ),
        ),
    ]
