# Generated by Django 5.2.7 on 2025-10-23 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dentist_info_app", "0010_alter_booking_date_booking_contact"),
    ]

    operations = [
        migrations.AddField(
            model_name="dentist",
            name="City",
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
