# Generated by Django 5.2.7 on 2025-10-23 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dentist_info_app", "0011_dentist_city"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dentist",
            name="Profile_img",
            field=models.ImageField(
                blank=True, max_length=300, null=True, upload_to="images/"
            ),
        ),
    ]
