# Generated by Django 5.2.5 on 2025-08-25 19:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Dentist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Full_name", models.CharField(max_length=200)),
                (
                    "User_id",
                    models.CharField(
                        max_length=6,
                        validators=[django.core.validators.MinLengthValidator(6)],
                    ),
                ),
                ("Speciality", models.CharField(max_length=20)),
                (
                    "Experience",
                    models.TextField(blank=True, max_length=1000, null=True),
                ),
            ],
        ),
    ]
