# Generated by Django 5.2.5 on 2025-08-31 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dentist_info_app", "0003_booking_alter_dentist_profile_img"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="Appointment_ID",
            field=models.CharField(default=1, max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
