# Generated by Django 5.2.5 on 2025-09-20 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dentist_info_app", "0005_booking_date_now"),
    ]

    operations = [
        migrations.RenameField(
            model_name="booking",
            old_name="Date",
            new_name="Date_booking",
        ),
        migrations.AlterField(
            model_name="booking",
            name="Appointment_ID",
            field=models.CharField(default=300556, max_length=10, unique=True),
        ),
    ]
