# Generated by Django 5.2.6 on 2025-09-29 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dentist_info_app", "0008_alter_booking_dentist_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="Dentist_ID",
        ),
        migrations.AddField(
            model_name="booking",
            name="Dentist",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Dentist_info",
                to="dentist_info_app.dentist",
            ),
            preserve_default=False,
        ),
    ]
